public class fromJSON{
	public cls_entries[] entries{get; set;}
	public String cursor{get; set;}	//AAGbORnkYEtze-zCOhpw7WJHA6A5j0DufiuoVqfiBSA4oKHS60xbvPzZ50DcWaL4Z_0qjjG2cNYSGpZzNXmEyzZYD1cdfReT30TKYQdpZDyiZs5jis_1f28yftzn0g-a9r_ug9QnSMgXPSnCyikbOtngWwYDx44EbtNRqMAkrc7Nuw
	public boolean has_more{get; set;}	

public	class cls_entries{
	//blic String .tag{get; set;}		//folder
	public String name{get; set;}		//New folder
	public String path_lower{get; set;}		///new folder
	public String path_display{get; set;}		///New folder
	public String id{get; set;}		//id:II3zn9kP53AAAAAAAAAADQ
}
}