public class TesttttttttttClasssssss {
	
    public Static void onlyForTestPur11(List<String>   listCon1){
       // RecursiveTriggerHandler
       System.debug('Come==Here==');
        RecursiveTriggerHandler.onlyForTestPur1222(listCon1);
    }
    
    
    
    @future
    public Static void onlyForTestPur1222(List<String> listCon1){
       //TesttttttttttClasssssss.onlyForTestPur11(listCon1);
       System.debug('Come==Here==Futurr==');
    }
}